apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-db-deployment
spec:
  template:
    metadata:
      name: news-db
      labels:
        app: news-db
    spec:
      containers:
        - name: news-db-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: news-db